### PR TITLE
implement junctions to components.py

### PR DESCRIPTION
**Pull request by jvwilliams23**
Implemented junctions required for thermal-hydraulic modelling.

### CODE REVIEW

**Comment by makeclean** [comment]
Hi @jvwilliams23 any chance you could add a test?

**Comment by jvwilliams23** [comment]
Hi @makeclean . Yeah I could try do an automated unit test based on one of the input files provided by MOOSE? The parser should reproduce the input script if properly implemented. Does it sound ok?

**Comment by jvwilliams23** [comment]
Hi @makeclean I added some tests in a similar style to already existing ones.

**Comment by makeclean** [comment]
Let me know when this is ready to merge

**Comment by jvwilliams23** [comment]
Hi Andy. This is ready IMO.
________________________________

**Comment by makeclean** [comment]
Perfect, thanks @jvwilliams23

**Pull request merged**
